version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yaltrip
      POSTGRES_PASSWORD: PeDTifs
      POSTGRES_DB: yaltrip
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432