spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/yaltrip
    username: yaltrip
    password: PeDTifs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
jwt:
  key: ACFAADEDA4B97B4C0817C14D7C0E91C9B5E2C522C6DCBE5BE0AA98E86351F0A7